---

- name: Download latest stable version of Memcache
  get_url:
    url: "{{ memcached_source_url }}{{ memcached_source_version }}.tgz"
    dest: "{{ php_source_clone_dir }}"

- name: Extract downloaded memcache tar.gz file
  unarchive:
    src: "{{ php_source_clone_dir }}{{ memcached_source_version }}.tgz"
    dest: "{{ php_source_clone_dir }}"
    remote_src: yes

- name: Build configure script.
  command: >
    "{{ php_source_install_path }}/bin/phpize"
    chdir={{ php_source_clone_dir }}/{{ memcached_source_version }}

- name: Run configure script.
  command: >
    {{ memcached_configure_command }}
    chdir={{ php_source_clone_dir }}/{{ memcached_source_version }}

- name: Run make
  command: >
    {{ item }}
    chdir={{ php_source_clone_dir }}/{{ memcached_source_version }}
  with_items:
    - make

- name: Find location of opcache.so
  shell: "find {{ php_source_install_path }} -name opcache.so -printf '%h\n'"
  changed_when: false
  failed_when: false
  register: opcache_so_location

- name: Copy memcached module to PHP location
  copy:
    src: "{{ php_source_clone_dir }}/{{ memcached_source_version }}/modules/memcached.so"
    dest: "{{ opcache_so_location.stdout }}"
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
    remote_src: yes
