---

- name: Stop PHP-FPM
  shell: "sh -c {{ sh_fpm_stop }}"

- name: Extract Source file
  unarchive:
    src: "{{ playbook_dir }}/{{ compressed_dir }}/{{ gml_source_php_file }}"
    dest: "{{ gml_source_path }}"
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
    remote_src: yes

- name: make File executable
  file:
    path: "{{ php_source_install_path }}/bin/{{ item }}"
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
    mode: "0750"
  loop:
    - php
    - php-cgi
    - php-fpm
    - phpdbg

- name: Ensure php executable is symlinked into a standard path.
  file:
    src: "{{ php_source_install_path }}/bin/{{ item }}"
    dest: "{{ gml_source_path }}/bin/{{ item }}"
    state: link
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
    force: yes
  loop:
    - php
    - php-fpm
    - phpize
    - php-cgi
    - php-config

- name: Restart PHP-FPM in Systemctl
  shell: "sh -c {{ sh_fpm_start }}"