---

 - name: Check symlink for systemd HL7 WEB Backup Service
   stat:
    path: "/etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.service"
   register: register_hl7_web_backup_hospital_service

 - name: Check symlink for systemd HL7 WEB Backup Service
   stat:
    path: "/etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.timer"
   register: register_hl7_web_backup_hospital_timer

 - name: Ensure Backup Dir Exists
   file:
     path: "{{ hl7_web_code_backup_dir }}"
     state: directory
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'

 - name: Ensure Backup Dir Exists in shared drive (JHS)
   file:
     path: "{{ shared_archive_hl7_code_backup_dir }}"
     state: directory
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'
   when:
      - cluster == 'jhs'

 - name: Ensure Backup Dir Exists in shared drive
   file:
     path: "{{ shared_drive_hl7_code_backup_dir }}"
     state: directory
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'
   when:
      - cluster != 'jhs'
      
 - name: Copy HL7 Web Backup Script
   template:
     src: "roles/timers/templates/scripts/hl7_web_code_backup.sh.j2"
     dest: "{{ script_location }}{{ hl7_web_code_backup_script }}"
     owner: "{{ code_user}}"
     group: "{{ code_user}}"
     mode: '0750' 

 - name: Copy HL7 Web Backup Folder list
   template:
     src: roles/timers/templates/scripts/hl7_web_exclude_files.txt.j2
     dest: "{{ script_location }}{{ hl7_web_exclude_script }}"
     owner: "{{ code_user}}"
     group: "{{ code_user}}"
     mode: '0750' 

 - name: Export HL7 Web Backup Service
   template:
      src: roles/timers/templates/service/hl7_web_backup.service.j2
      dest: "{{ gml_source_path }}/startup/hl7_web_backup_{{ cluster }}.service"
      owner: "{{ code_user }}"
      group: "{{ code_user }}"
      mode: '0750'

 - name: Copy HL7 Web Backup Service
   command: 'sudo cp -f {{ gml_source_path }}/startup/hl7_web_backup_{{ cluster }}.service /usr/lib/systemd/system/'

 - name: Create link for systemd - HL7 Web backup
   command: "{{ item }}"
   with_items:
     - 'sudo ln -s /usr/lib/systemd/system/hl7_web_backup_{{ cluster }}.service /etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.service'
     - 'sudo chown root:root /etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.service'
     - 'sudo chmod 750 /etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.service'
   when: not register_hl7_web_backup_hospital_service.stat.exists
   notify: enable hl7_web_backup

 - name: Export HL7 Web Backup Timer
   template:
      src: roles/timers/templates/timer/hl7_web_backup.timer.j2
      dest: "{{ gml_source_path }}/startup/hl7_web_backup_{{ cluster }}.timer"
      owner: "{{ code_user }}"
      group: "{{ code_user }}"
      mode: '0750'

 - name: Copy HL7 Web Backup Timer
   command: 'sudo cp -f {{ gml_source_path }}/startup/hl7_web_backup_{{ cluster }}.timer /usr/lib/systemd/system/'

 - name: Create link for systemd - timer
   command: "{{ item }}"
   with_items:
     - 'sudo ln -s /usr/lib/systemd/system/hl7_web_backup_{{ cluster }}.timer /etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.timer'
     - 'sudo chown root:root /etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.timer'
     - 'sudo chmod 750 /etc/systemd/system/multi-user.target.wants/hl7_web_backup_{{ cluster }}.timer'
   when: not register_hl7_web_backup_hospital_timer.stat.exists
   notify: start hl7_web_backup.timer