---

 - name: Check sysmlink for systemd Web Backup Service
   stat:
    path: "/etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.service"
   register: register_web_backup_hospital_service

 - name: Check sysmlink for systemd Web Backup Timer
   stat:
    path: "/etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.timer"
   register: register_web_backup_hospital_timer

 - name: Ensure Backup Dir Exists
   file:
     path: "{{ web_code_backup_dir }}"
     state: directory
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'
     
 - name: Ensure Backup Dir Exists in shared drive (JHS)
   file:
     path: "{{ item }}"
     state: directory
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'
   with_items:
      - "{{ shared_archive_web_code_backup_dir }}"
   when:
      - cluster == 'jhs'

 - name: Ensure Backup Dir Exists in shared drive
   file:
     path: "{{ item }}"
     state: directory
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'
   with_items:
      - "{{ shared_drive_web_code_backup_dir }}"
   when:
      - cluster != 'jhs'

 - name: Copy Web Backup Script
   template:
     src: "templates/scripts/web_code_backup.sh.j2"
     dest: "{{ script_location }}{{ web_code_backup_script }}"
     owner: "{{ code_user}}"
     group: "{{ code_user}}"
     mode: '0750' 

 - name: Copy Web Backup Folder list
   template:
     src: "templates/scripts/web_exclude_files.txt.j2"
     dest: "{{ script_location }}{{ web_exclude_script }}"
     owner: "{{ code_user}}"
     group: "{{ code_user}}"
     mode: '0750' 

 - name: Export Web Backup Service {{ gml_source_path }}/startup/
   template:
      src: roles/timers/templates/service/web_backup.service.j2
      dest: "{{ gml_source_path }}/startup/web_backup_{{ hospital }}.service"
      owner: "{{ code_user }}"
      group: "{{ code_user }}"
      mode: '0750'

 - name: Copy Web Backup Service script to systemd
   command: 'sudo cp -f {{ gml_source_path }}/startup/web_backup_{{ hospital }}.service /usr/lib/systemd/system/'
 
 - name: Create link for systemd - Web Backup Service
   command: "{{ item }}"
   with_items:
     - 'sudo ln -s /usr/lib/systemd/system/web_backup_{{ hospital }}.service /etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.service'
     - 'sudo chown root:root /etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.service'
     - 'sudo chmod 750 /etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.service'
   when: not register_web_backup_hospital_service.stat.exists
   notify: enable web_backup

 - name: Export Web Backup Timer
   template: 
      src: roles/timers/templates/timer/web_backup.timer.j2 
      dest: "{{ gml_source_path }}/startup/web_backup_{{ hospital }}.timer"
      owner: "{{ code_user }}"
      group: "{{ code_user }}"
      mode: '0750'

 - name: Copy Web Backup Time script to systemd
   command: 'sudo cp -f {{ gml_source_path }}/startup/web_backup_{{ hospital }}.timer /usr/lib/systemd/system/'

 - name: Create link for systemd - Web Backup Timer
   command: "{{ item }}"
   with_items:
     - 'sudo ln -s /usr/lib/systemd/system/web_backup_{{ hospital }}.timer /etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.timer'
     - 'sudo chown root:root /etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.timer'
     - 'sudo chmod 750 /etc/systemd/system/multi-user.target.wants/web_backup_{{ hospital }}.timer'
   when: not register_web_backup_hospital_timer.stat.exists
   notify: start web_backup.timer