---

 - name: Check sysmlink for systemd hms-logs Transfer Service
   stat:
    path: "/etc/systemd/system/multi-user.target.wants/hms-logs_transfer.service"
   register: register_hms_logs_transfer_service 

 - name: Check sysmlink for systemd hms-logs Transfer Timer
   stat:
    path: "/etc/systemd/system/multi-user.target.wants/hms-logs_transfer.timer"
   register: register_hms_logs_transfer_timer
   
 - name: Copy logfiles transfer script
   template:
     src: roles/timers/templates/scripts/hms_logs_transfer.sh.j2
     dest: "{{ script_location }}{{ hospital }}_hms-logs_transfer.sh"
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'

 - name: Copy logfiles postrotate script
   template:
     src: roles/timers/templates/scripts/postrotate_pgsql.sh.j2
     dest: "{{ script_location }}/postrotate_pgsql_{{ hospital }}.sh"
     owner: "{{ code_user }}"
     group: "{{ code_user }}"
     mode: '0750'

 - name: Export HMS Web logs Service
   template: 
      src: roles/timers/templates/service/hms-logs_transfer.service.j2 
      dest: "{{ gml_source_path }}/startup/hms-logs_transfer.service"
      owner: "{{ code_user }}"
      group: "{{ code_user }}"
      mode: '0750'

 - name: Copy HMS Web logs Service
   command: 'sudo cp -f {{ gml_source_path }}/startup/hms-logs_transfer.service /usr/lib/systemd/system/'

 - name: Create link for systemd - HMS logs transfer
   command: "{{ item }}"
   with_items:
     - 'sudo ln -s /usr/lib/systemd/system/hms-logs_transfer.service /etc/systemd/system/multi-user.target.wants/hms-logs_transfer.service'
     - 'sudo chown root:root /etc/systemd/system/multi-user.target.wants/hms-logs_transfer.service'
     - 'sudo chmod 750 /etc/systemd/system/multi-user.target.wants/hms-logs_transfer.service'
   when: not register_hms_logs_transfer_service.stat.exists
   notify: enable hms-logs_transfer
 
 - name: Export HMS Web logs Timer
   template: 
      src: roles/timers/templates/timer/hms-logs_transfer.timer.j2
      dest: "{{ gml_source_path }}/startup/hms-logs_transfer.timer"
      owner: "{{ code_user }}"
      group: "{{ code_user }}"
      mode: '0750'
     
 - name: Copy HMS Web logs Timer
   command: 'sudo cp -f {{ gml_source_path }}/startup/hms-logs_transfer.timer /usr/lib/systemd/system/'

 - name: Create link for systemd - HMS logs timer
   command: "{{ item }}"
   with_items:
     - 'sudo ln -s /usr/lib/systemd/system/hms-logs_transfer.timer /etc/systemd/system/multi-user.target.wants/hms-logs_transfer.timer'
     - 'sudo chown root:root /etc/systemd/system/multi-user.target.wants/hms-logs_transfer.timer'
     - 'sudo chmod 750 /etc/systemd/system/multi-user.target.wants/hms-logs_transfer.timer'
   when: not register_hms_logs_transfer_timer.stat.exists
   notify: start hms-logs_transfer.timer

 - name: Reload systemd
   command: "{{ sh_systemctl }} daemon-reload"

 - name: Restart HMS logs services and timer 
   command: "{{ sh_systemctl }} restart {{ sh_web_logs_svc }} {{ sh_web_logs_tmr }}"