- name: Check old Postgresql Version
  shell: "{{ gml_source_path }}/bin/psql -V | awk '{print $3}'"
  register: old_pgsql_version
  tags: post_upgrade_pgsql

- name: Stop Postgresql services
  shell: sh -c "{{ sh_pgsql_stop }}"

- name: Extract Source file
  unarchive:
    src: "{{ playbook_dir }}/{{ compressed_dir }}/{{ gml_source_psql_file }}"
    dest: "{{ gml_source_path }}"
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
    remote_src: yes

- name: Ensure Apache executable is symlinked into a standard path.
  file:
    src: "{{ item }}"
    dest: "{{ gml_source_path }}/bin/{{ item | basename }}"
    state: link
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
    force: yes
  with_fileglob:
    - "{{ pgsql_install_path }}/bin/*"

- name: Start Postgresql services
  shell: sh -c "{{ sh_pgsql_start }}"

- name: Compress old Postgresql Version
  become: yes
  become_user: root
  become_method: sudo
  archive:
    path: "{{ gml_source_path }}/postgres-{{old_pgsql_version.stdout}}"
    dest: "{{ gml_source_path }}/postgres-{{old_pgsql_version.stdout}}.tar.gz"
    owner: "{{ code_user }}"
    group: "{{ code_user }}"
  tags: post_upgrade_pgsql

- name: Remove old Postgresql folder directory
  become: yes
  become_user: root
  become_method: sudo
  file:
    state: absent
    path: "{{ gml_source_path }}/postgres-{{old_pgsql_version.stdout}}"
  tags: post_upgrade_pgsql